// OpenAI Batch API limit
export const BATCH_API_LIMIT = 50000;

// Stage constants for state machine
export const STAGES = {
  PREP: "PREP",
  QUERY_GEN_UPLOAD: "QUERY_GEN_UPLOAD",
  QUERY_GEN_POLL: "QUERY_GEN_POLL",
  QUERY_GEN_PROCESS: "QUERY_GEN_PROCESS",
  PUB_DISCOVERY: "PUB_DISCOVERY",
  RESULT_GEN_PREPARATION: "RESULT_GEN_PREPARATION",
  RESULT_GEN_UPLOAD: "RESULT_GEN_UPLOAD",
  RESULT_GEN_POLL: "RESULT_GEN_POLL",
  RESULT_GEN_PROCESS: "RESULT_GEN_PROCESS",
  FINALIZE: "FINALIZE",
  COST_CALCULATION: "COST_CALCULATION",
  COMPLETE: "COMPLETE",
};
